---UDF is similar but different to StorProc---

---Scalar Function(single data value), Table-Value Functions, System Functions(cannot not be modified)
---Syst Func msdn.mircrosoft.com/en-us/library/ms191007.aspx

SELECT * FROM tableName

CREATE FUNCTION YTDSALES()
RETURN MONEY
AS
BEGIN
DECLARE @YTDSALES MONEY
SELECT @YTDSALES = SUM(colName) FROM tableName
RETURN @YTDSALES
END

DECLARE @YTDRESULT  AS MONEY
SELECT @YTDRESULT = dbo.YTDSALES()
PRINT @YTDRESULT

--clean up functions
DROP FUNCTION YTDSALES

--PARAMETERIZED FUNCTIONS
SELECT * FROM tableName

CREATE FUNCTION YTD_GROUP
(@GROUP VARCHAR(50))

RETURN MONEY
AS
BEGIN
DECLARE @YTDSALES AS MONEY
SELECT @YTDSALES = SUM(colName) FROM tableName
WHERE [GROUP] = @GROUP
RETURN @YTDSALES
END

DECLARE @RESULTS MONEY
SELECT @RESULT = dbo.colName('USA')
PRINT @RESULTS

--clean up
DROP FUNCTION YTD_GROUP

----FUNCTIONS RETURNING TABLES-----
CREATE FUNCTION ST_TABVALUED
(@colName INT)
RETURNS TABLE
AS RETURN
SELECT colName, colName1, colName2, [Group]
FROM tableName
WHERE colName = @colName

SELECT colName, [GROUP]





